---

- hosts: all
  become: true
  pre_tasks:

  - name: install update for CentOS
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install update for Debian and Ubuntu
    tags: always
    apt:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
