#!/bin/bash

# Cesta k souboru .bash_prompt
BASH_PROMPT_PATH="$HOME/.bash_prompt"

# Obsah promptu
PROMPT_CONTENT='BRACKET_COLOR="\[\033[38;5;35m\]"
CLOCK_COLOR="\[\033[38;5;35m\]"
JOB_COLOR="\[\033[38;5;33m\]"
PATH_COLOR="\[\033[38;5;33m\]"
LINE_BOTTOM="\342\224\200"
LINE_BOTTOM_CORNER="\342\224\224"
LINE_COLOR="\[\033[38;5;248m\]"
LINE_STRAIGHT="\342\224\200"
LINE_UPPER_CORNER="\342\224\214"
END_CHARACTER="|"

tty -s && export PS1="$LINE_COLOR$LINE_UPPER_CORNER$LINE_STRAIGHT$LINE_STRAIGHT$BRACKET_COLOR[$CLOCK_COLOR\t$BRACKET_COLOR]$LINE_COLOR$LINE_STRAIGHT$BRACKET_COLOR[$JOB_COLOR\j$BRACKET_COLOR]$LINE_COLOR$LINE_STRAIGHT$BRACKET_COLOR[\H:\]$PATH_COLOR\w$BRACKET_COLOR]\n$LINE_COLOR$LINE_BOTTOM_CORNER$LINE_STRAIGHT$LINE_BOTTOM$END_CHARACTER\[$(tput sgr0)\] "'

# Zapis obsahu promptu do souboru .bash_prompt
echo "$PROMPT_CONTENT" > "$BASH_PROMPT_PATH"

# Pridani prikazu pro nacteni .bash_prompt do .bashrc, pokud tam uz neni
if ! grep -q "source ~/.bash_prompt" "$HOME/.bashrc"; then
    echo "source ~/.bash_prompt" >> "$HOME/.bashrc"
    echo "Nastaveni promptu dokonceno. Restartujte terminal nebo pouzijte prikaz source ~/.bashrc pro aplikovani zmen."
else
    echo "Prompt uz je nastaven."
fi
